# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fr.doctrine
canonical: https://interop.esante.gouv.fr/ig/doctrine # the last part of canonical and id must be the same
name: DoctrineCISIS
title: Doctrine et gouvernance du cadre d'interopérabilité des systèmes d'informations en santé (CI-SIS)
publisher:
  name: ANS
  url: https://esante.gouv.fr
status: draft
version: 0.1.0-ballot # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

parameters:
    shownav: 'true'

pages:
    index.md:
        title: Accueil
    doctrine.md:
        title: Doctrine
    trajectoire-iop.md:
        title: Trajectoire interopérabilité
    elaboration.md:
        title: Méthode d'élaboration des échanges fonctionnels
    choix-standard.md:
        title: Choix des normes et standard
    cycle-de-vie.md:
        title: Cycle de vie des spécifications
    comitologie.md:
        title: Comitologie du CI-SIS
    interactions-ecosysteme.md:
        title: Interactions avec l'écosystème
    ebe-cp.md:
        title: Expression des besoins (EBE) et gestion des Change Proposals (CP)
    up-externe.md:
        title: Unité de production externe
    change-log.md:
        title: "Historique des versions"


menu:
    Accueil: index.html
    Doctrine du CI-SIS: 
        Doctrine: doctrine.html
        Trajectoire interopérabilité: trajectoire-iop.html
        Méthode d'élaboration des échanges fonctionnels: elaboration.html
        Choix des normes et standard: choix-standard.html
        Cycle de vie des spécifications: cycle-de-vie.html
    Gouvernance du CI-SIS:
        Comitologie : comitologie.html
        Interactions avec l'écosystème: interactions-ecosysteme.html
        Expression des besoins et Change Proposals: ebe-cp.html
        Unité de production externe: up-externe.html
    Historique des versions: change-log.html
    Documentation des IGs: new-tab https://interop.esante.gouv.fr/ig/documentation/
