# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fr.doctrine
canonical: https://interop.esante.gouv.fr/ig/doctrine # the last part of canonical and id must be the same
name: DoctrineCISIS # Should be an acronym
title: Doctrine du CI-SIS
publisher:
  name: ANS
  url: https://esante.gouv.fr
status: draft
version: 0.1.0 # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

parameters:
    shownav: 'true'

pages:
    index.md:
        title: Accueil
    doctrine-cisis.md:
        title: Doctrine du CI-SIS
    cycle-de-vie.md:
        title: Cycle de vie
    trajectoire-interop.md:
        title: Trajectoire interopérabilité
    interactions-ecosysteme.md:
        title: Interactions avec l'écosystème
    gestion-cp.md:
        title: Gestion des changements
    gestion-ebe.md:
        title: Expression des besoin
    connaissance-medicale.md:
        title: Connaissance médicale

menu:
    Accueil: index.html
    Doctrine du CI-SIS: 
        Doctrine du ci-sis: doctrine-cisis.html
        Cycle de vie: cycle-de-vie.html
        Trajectoire interopérabilité: trajectoire-interop.html
        Connaissance médicale: connaissance-medicale.html
    Gouvernance du CI-SIS:
        Interactions avec l'écosystème: interactions-ecosysteme.html
        Gestion des changements: gestion-cp.html
        Expression des besoins : gestion-ebe.html
    

    Documentation des IGs: new-tab https://interop.esante.gouv.fr/ig/documentation/
