# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fr.doctrine
canonical: https://interop.esante.gouv.fr/ig/doctrine # the last part of canonical and id must be the same
name: DoctrineCISIS # Should be an acronym
title: Doctrine du CI-SIS
publisher:
  name: ANS
  url: https://esante.gouv.fr
status: draft
version: 0.1.0 # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

parameters:
    shownav: 'true'

pages:
    index.md:
        title: Accueil
    generalites.md:
        title: Généralités
    doctrine.md:
        title: Doctrine du CI-SIS
    elaboration.md:
        title: Méthode d'élaboration des échanges fonctionnels
    choix-standard.md:
        title: Choix des normes et standard
    cycle-de-vie.md:
        title: Cycle de vie des spécifications
    ebe-cp.md:
        title: Expression des besoins (EBE) et gestion des Change Proposals (CP)
    trajectoire-iop.md:
        title: Trajectoire interopérabilité
    up-externe.md:
        title: Unité de production externe
    interactions-ecosysteme.md:
        title: Interactions avec l'écosystème

menu:
    Accueil: index.html
    Doctrine: 
        Généralités: generalites.html
        Doctrine du ci-sis: doctrine.html
        Méthode d'élaboration des échanges fonctionnels: elaboration.html
        Choix des normes et standard: choix-standard.html
        Cycle de vie: cycle-de-vie.html
        Expression des besoins et Change Proposals: ebe-cp.html
        Trajectoire interopérabilité: trajectoire-iop.html
        Unité de production externe: up-externe.html
    Gouvernance:
        Interactions avec l'écosystème: interactions-ecosysteme.html

    Documentation des IGs: new-tab https://interop.esante.gouv.fr/ig/documentation/
