# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fr.doctrine
canonical: https://interop.esante.gouv.fr/ig/doctrine # the last part of canonical and id must be the same
name: DoctrineCISIS # Should be an acronym
title: Doctrine du CI-SIS
publisher:
  name: ANS
  url: https://esante.gouv.fr
status: draft
version: 0.1.0 # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

parameters:
    shownav: 'true'

pages:
    index.md:
        title: Accueil
    doctrine-cisis.md:
        title: Doctrine du CI-SIS
    impacts.md:
        title: Impacts sur la gouvernance du CI-SIS

menu:
    Accueil: index.html
    Doctrine du CI-SIS: doctrine-cisis.html
    Impacts sur la gouvernance du CI-SIS: impacts.html
    Documentation des IGs: new-tab https://interop.esante.gouv.fr/ig/documentation/
